# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
